apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplicacion
  namespace: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: aplicacion
        image: 192.168.5.3:5000/kubernetes/app:v0.3
        ports:
        - containerPort: 80
